name: Terraform Deployment

on:
   push:
     branches:
       - main

 jobs:
   terraform:
     name: Terraform
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
       AWS_REGION: 'ap-south-1'
     runs-on: ubuntu-latest
     environment: test
    
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up Terraform
       uses: hashicorp/setup-terraform@v1
       with:
         terraform_version: 1.0.0

     - name: Initialize Terraform
       run: terraform init
      
      
     - name: Plan Terraform changes
       run: terraform plan -out=tfplan

     # Add a prompt to ask the user whether to apply or destroy changes
     - name: Apply Terraform changes
       run: terraform apply --auto-approve

     - name: Clean up
       run: rm tfplan
